apiVersion: apps/v1
kind: Deployment
metadata:
  name: consportals-sa-mobily-dsp-a3gw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: dsp-a3gw
  template:
    metadata:
      labels:
        component: dsp-a3gw
    spec:
      containers:
        - name: dsp-a3gw
          image: mersin.telenity.com/com/telenity/consportals-sa-mobily-dsp-a3gw:1.0.0.1
          ports:
            - containerPort: 8444
            - containerPort: 8445