apiVersion: v1
kind: Service
metadata:
  name: consportals-sa-mobily-dsp-partnerportal-service
spec:
  type: ClusterIP
  selector:
    component: dsp-partnerportal
  ports:
    - port: 8082
      targetPort: 8082