apiVersion: v1
kind: Service
metadata:
  name: consportals-sa-mobily-dsp-ccportal-service
spec:
  type: ClusterIP
  selector:
    component: dsp-ccportal
  ports:
    - port: 8081
      targetPort: 8081