apiVersion: v1
kind: Service
metadata:
  name: consportals-sa-mobily-dsp-adminportal-service
spec:
  type: ClusterIP
  selector:
    component: dsp-adminportal
  ports:
    - port: 8080
      targetPort: 8080