apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-adminportal-service
  labels:
    app.kubernetes.io/name: vcp-adminportal
    app.kubernetes.io/part-of: consolportals
spec:
  type: ClusterIP
  selector:
    component: vcp-adminportal
  ports:
    - name: http   # <-- this was missing
      port: 8080
      targetPort: 8080
