apiVersion: v1
kind: Pod
metadata:
  name: consolportals-sa-stc-vcp-ccportal
  labels:
    component: vcp-ccportal
spec:
  containers:
    - name: vcp-ccportal
      image: mersin.telenity.com/com/telenity/consolportals-sa-stc-vcp-ccportal:1.0.0.1
      ports:
        - containerPort: 8081
