apiVersion: v1
kind: Pod
metadata:
  name: consolportals-sa-stc-vcp-adminportal
  labels:
    component: vcp-adminportal
spec:
  containers:
    - name: vcp-adminportal
      image: nexus.telenity.com/com/telenity/consolportals-sa-stc-vcp-adminportal:1.0.0.2
      ports:
        - containerPort: 8080
