apiVersion: v1
kind: Pod
metadata:
  name: consportals-sa-mobily-vcp-a3gw
  labels:
    component: vcp-a3gw
spec:
  containers:
    - name: vcp-a3gw
      # Fixed image name to match deployment
      image: mersin.telenity.com/com/telenity/consportals-sa-mobily-vcp-a3gw:1.0.0.1
      ports:
        - containerPort: 8444
        - containerPort: 8445
