apiVersion: v1
kind: Pod
metadata:
  name: consportals-sa-mobily-vcp-adminportal
  labels:
    component: vcp-adminportal
spec:
  containers:
    - name: vcp-adminportal
      image: mersin.telenity.com/com/telenity/consportals-sa-mobily-vcp-adminportal:1.0.0.1
      ports:
        - containerPort: 8080