{{- if .Values.a3gw.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consolportals-sa-stc-vcp-a3gw-deployment
  namespace: {{ include "consolportals.namespace" . }}
spec:
  replicas: {{ .Values.a3gw.replicaCount }}
  selector:
    matchLabels:
      component: vcp-a3gw
  template:
    metadata:
      annotations:
        checksum/a3gw-config: {{ include (print $.Template.BasePath "/a3gw-configmap.yaml") . | sha256sum }}
        checksum/a3gw-secret: {{ include (print $.Template.BasePath "/a3gw-secret.yaml") . | sha256sum }}
      labels:
        component: vcp-a3gw
    spec:
      containers:
        - name: vcp-a3gw
          image: "{{ .Values.a3gw.image.repository }}:{{ .Values.a3gw.image.tag }}"
          imagePullPolicy: {{ .Values.a3gw.image.pullPolicy }}
          ports:
            - containerPort: 8444
            - containerPort: 8445
          volumeMounts:
            - name: a3gw-conf
              mountPath: /space/a3gw/src/conf
              readOnly: true
            - name: a3gw-logs
              mountPath: /space/a3gw/logs

        {{- if .Values.a3gw.logging.tailSidecar.enabled }}
        - name: a3gw-log-tail
          image: {{ .Values.a3gw.logging.tailSidecar.image }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-lc"]
          args:
            - >
              echo "[a3gw-log-tail] waiting for log files..." ;
              mkdir -p /space/a3gw/logs ;
              ls -lah /space/a3gw/logs || true ;
              tail -F /space/a3gw/logs/*.log
          volumeMounts:
            - name: a3gw-logs
              mountPath: /space/a3gw/logs
        {{- end }}

      volumes:
        - name: a3gw-logs
          emptyDir: {}
        - name: a3gw-conf
          projected:
            sources:
              - configMap:
                  name: {{ include "vcp.a3gw.configmapName" . }}
              - secret:
                  name: {{ include "vcp.a3gw.secretName" . }}
  {{- end }}
