{{- if .Values.a3gw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-a3gw-service
  namespace: {{ include "consolportals.namespace" . }}
spec:
  type: {{ .Values.service.a3gw.type }}
  selector:
{{ toYaml .Values.service.a3gw.selector | indent 4 }}
  ports:
{{ toYaml .Values.service.a3gw.ports | indent 4 }}
{{- end }}
