{{- range $portal := list "adminportal" "ccportal" "partnerportal" }}
{{- $portalConfig := index $.Values $portal }}
{{- if $portalConfig.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consolportals.deploymentName" (dict "component" $portal) }}
  labels:
    {{- include "consolportals.componentLabels" (dict "component" (printf "vcp-%s" $portal) "context" $) | nindent 4 }}
spec:
  replicas: {{ $portalConfig.replicaCount }}
  selector:
    matchLabels:
      {{- include "consolportals.componentSelectorLabels" (dict "component" (printf "vcp-%s" $portal) "context" $) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "consolportals.componentSelectorLabels" (dict "component" (printf "vcp-%s" $portal) "context" $) | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "consolportals.serviceAccountName" $ }}
      {{- end }}
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ printf "vcp-%s" $portal }}
          {{- with $.Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "consolportals.image" (dict "image" $portalConfig.image "Chart" $.Chart) }}
          imagePullPolicy: {{ $portalConfig.image.pullPolicy }}
          ports:
            - containerPort: {{ $portalConfig.containerPort }}
              protocol: TCP
          {{- with $portalConfig.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
